/**:
  ros__parameters:
    image_topic: /camera/image_raw
    service_name: /find_object
    feedback_topic: /camera_feedback
    enable_feedback_bridge: true
    feedback_host: 127.0.0.1
    feedback_port: 65434
    feedback_interval_sec: 0.5
    requested_mode_default: normal
    workspace_yaml: /home/jeffliu/SOMA/soma-arm/config/calibration/workspace.yaml
    eye_to_hand_yaml: /home/jeffliu/SOMA/soma-arm/config/calibration/eye_to_hand.yaml
